apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-watcher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-watcher
  template:
    metadata:
      labels:
        app: node-watcher
    spec:
      serviceAccountName: kubesphere-cluster-admin
      containers:
        - name: node-watcher
          image: harbor.dev.thingsdao.com/edgewize/node-watcher:v0.0.1
          command:
            - /root/nodeWatcher
            - --memoryThreshold=40.0
